server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/fresh_food_shop
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # dev: update | prod: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: Asia/Ho_Chi_Minh

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
file:
  upload-dir: uploads
app:
  base-url: http://localhost:8080
jwt:
  secret: QWxhZGRpbjpPcGVuU2VzYW1lU2VjcmV0S2V5MTIzNDU2
  expiration: 86400000

